com.auth0:java-jwt = 4.5.1
com.fasterxml.jackson.*:* = 2.21.2
com.fasterxml.jackson.core:jackson-annotations = 2.21
com.github.ben-manes.caffeine:caffeine = 3.2.3
com.google.auto.service:auto-service = 1.1.1
com.google.errorprone:error_prone_core = 2.42.0
com.google.googlejavaformat:google-java-format = 1.28.0
com.google.guava:guava = 33.6.0-jre
com.jakewharton.nopen:* = 1.0.1
com.markelliot.barista.tracing:barista-tracing = 0.132.0
com.markelliot.result:result = 0.134.0
com.palantir.conjure.java:* = 8.74.0
com.palantir.javapoet:javapoet = 0.12.0
io.prometheus:prometheus-metrics-* = 1.5.1
io.undertow:undertow-core = 2.3.24.Final
org.apache.logging.log4j:* = 2.25.3
org.assertj:assertj-core = 3.27.7
org.junit.jupiter:junit-jupiter = 6.0.3
org.slf4j:* = 2.0.17
