com.auth0:java-jwt = 4.5.0
com.fasterxml.jackson.*:* = 2.18.2
com.github.ben-manes.caffeine:caffeine = 3.2.0
com.google.auto.service:auto-service = 1.1.1
com.google.errorprone:error_prone_core = 2.36.0
com.google.googlejavaformat:google-java-format = 1.25.2
com.google.guava:guava = 33.4.0-jre
com.jakewharton.nopen:* = 1.0.1
com.markelliot.barista.tracing:barista-tracing = 0.74.0
com.markelliot.result:result = 0.75.0
com.palantir.conjure.java:* = 8.42.0
com.squareup:javapoet = 1.13.0
io.undertow:undertow-core = 2.3.18.Final
org.apache.logging.log4j:* = 2.24.3
org.assertj:assertj-core = 3.27.3
org.junit:junit-bom = 5.11.4
org.junit.jupiter:junit-jupiter-engine = 5.11.4
org.slf4j:* = 2.0.16

