com.auth0:java-jwt = 4.4.0
com.fasterxml.jackson.*:* = 2.17.2
com.github.ben-manes.caffeine:caffeine = 3.1.8
com.google.auto.service:auto-service = 1.1.1
com.google.errorprone:error_prone_core = 2.29.0
com.google.googlejavaformat:google-java-format = 1.22.0
com.google.guava:guava = 33.2.1-jre
com.jakewharton.nopen:* = 1.0.1
com.markelliot.barista.tracing:barista-tracing = 0.74.0
com.markelliot.result:result = 0.75.0
com.palantir.conjure.java:* = 8.23.0
com.squareup:javapoet = 1.13.0
io.undertow:undertow-core = 2.3.15.Final
org.apache.logging.log4j:* = 2.23.1
org.assertj:assertj-core = 3.26.3
org.junit:junit-bom = 5.11.0-M2
org.junit.jupiter:junit-jupiter-engine = 5.11.0-M2
org.slf4j:* = 2.0.13

