name: autorelease
on:
  workflow_dispatch: {}
  schedule:
    # check at 11am every day
    - cron: '0 11 * * *'
jobs:
  autorelease:
    name: autorelease
    runs-on: ubuntu-latest
    steps:
      - name: Generate token
        id: token
        uses: actions/create-github-app-token@v3
        with:
          app-id: ${{ secrets.MELLBOT_APP_ID }}
          private-key: ${{ secrets.MELLBOT_PK }}
      - name: autorelease
        uses: markelliot/autorelease@v3
        with:
          github-token: ${{ steps.token.outputs.token }}
          # maximum number of days since last release
          max-days: 7
