name: autosquash
on:
  pull_request:
    types:
      - opened
      - synchronized
      - reopened
      - edited
      - labeled
      - unlabeled
      - ready_for_review
jobs:
  autosquash:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: theoremlp/autosquash@v1
        with:
          github-token: ${{ secrets.GH_PUSH_TO_REPO_TOKEN }}
          pull-request-number: ${{ github.event.pull_request.number }}
          squash-commit-title: "${{ github.event.pull_request.title }} (#${{ github.event.pull_request.number }})"
          squash-commit-message: "${{ github.event.pull_request.body }}"
          do-not-merge-label: "do not merge"
          # the setup for this repo is:
          #  - all markelliot's PRs are auto-approved using required-reviewers
          #  - if we don't ignore markelliot for autosquash, all PRs will merge on first successful build
          # ignoring markelliot here leaves self-merge on the table and prevents an unexpected automerge
          ignore-author: markelliot
