name: Required Reviewers
on:
  pull_request: {}
  pull_request_review: {}
jobs:
  required-reviewers:
    name: Required Reviewers
    runs-on: ubuntu-latest
    steps:
      - name: required-reviewers
        uses: theoremlp/required-reviews@v2
        with:
          github-token: ${{ secrets.GH_PUSH_TO_REPO_TOKEN }}
          post-review: true
