name: Required Reviewers
on:
  pull_request: {}
  pull_request_review: {}
jobs:
  required-reviewers:
    name: Required Reviewers
    runs-on: ubuntu-latest
    if: github.event.pull_request.head.repo.full_name == github.repository
    steps:
      - name: required-reviewers
        uses: theoremlp/required-reviews@v2
        with:
          github-token: ${{ secrets.REVIEW_TOKEN }}
          post-review: true
